import Head from 'next/head';
import AppProvider from 'utils/context';
import 'styles/globals.css';

// *** _APP -> ESTE COMPONENTE ES UN COMPONENTE QUE ENVUELVE AL INDEX
// ES UN TIPO LAYOUT DE NEXT 13, LAGO PARECIDO

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Frontend Challenge</title>
        <meta name="description" content="Generated by Lila Software Studio" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      {/* el Provider del context, para compartir estados en la app */}
      <AppProvider>
        <Component {...pageProps} />
      </AppProvider>
    </>
  );
}

export default MyApp;
